import './datatables/datatables.js'
import './dynamic-data/dynamic-data.js'
import './file/file.js'
import './modal/modal.js'
import './sidebar/sidebar.js'
import './sticky/sticky.js'
import './treeview/treeview.js'
