#!/usr/bin/env php
<?php

/**
 *------------------------------------------------------------------------------
 * Pluma Console
 *------------------------------------------------------------------------------
 *
 * Require the blacksmith/blacksmith Command.
 *
 * Try running `php pluma list` to view all available commands.
 */

require_once __DIR__ . '/blacksmith/blacksmith';
